#!/usr/bin/env sh

#capture all cli arguments to a single variable
CLJ_COMMAND=$*

# If the cljw is run with repl argument one will be launched from the official docker image
if [ "$CLJ_COMMAND" == "repl" ]; then
    echo Launching clojure REPL, use ctrl+c to exit...
    docker run -i --rm clojure:openjdk-8-tools-deps
else
    # otherwise pass arguments to the container clojure command
    docker run -i --rm \
    -v $(pwd)/.home:/root \
    -v $(pwd):/workspace \
    -w /workspace \
    --entrypoint=clojure clojure:openjdk-8-tools-deps $CLJ_COMMAND
fi